### ISSUE TITLE
Create a Fivetran Hook to interface the Fivetran API

### ISSUE THREAD

**Issue by pgzmnk** [fivetran/airflow-provider-fivetran#2]
Hooks interface Airflow modules (operators, sensors, etc.) with external resources exposed by the Fivetran API. Operators retrieve the connection from the hook, instead of repeatedly needing to declare the connection sessions. This architecture enables developers to handle the business logic of DAGs separately from how the authentication layer, request methods and endpoints, logging, retries, and timeouts are managed.

The [Python requests library](https://pypi.org/project/requests/) is commonly used to interface with APIs. The [Airflow HTTP hook is a good example of best practice](https://github.com/apache/airflow/blob/master/airflow/providers/http/hooks/http.py). It shows how to set up credentials and common methods. The hook takes in the http_conn_id as an argument and retrieves its corresponding parameters with the `self.get_connection()` method it inherits from BaseHook.

```
# Example of conn object retrieves connection values based on connection id
if self.http_conn_id:
    conn = self.get_connection(self.http_conn_id)

    if conn.host and "://" in conn.host:
        self.base_url = conn.host
```

In the case of the Fivetran Hook, this conn object would provide (API key and secret) parameters for the session object. See: [line 87 of the Fivetran Operator](https://github.com/fivetran/airflow-provider-fivetran/blob/main/airflow-provider-fivetran/operators/fivetran.py#L87).

Code for the hook should live within the hooks directory:
```
├── sample_provider
│   ├── __init__.py
│   ├── example_dags
│   │   ├── __init__.py
│   │   └── sample-dag.py
│   ├── hooks
│   │   ├── __init__.py
│   │   └── sample_hook.py
│   ├── operators
│   │   ├── __init__.py
│   │   └── sample_operator.py
│   └── sensors
│       ├── __init__.py
│       └── sample_sensor.py
└── setup.py
```

Note: In case you're wondering: it's possible to simply inherit from the HTTP hook to use the requests library. However, creating a custom hook provides dexterity and makes for a first-class user experience.

**Comment by crw** [comment]
Closed with https://github.com/fivetran/airflow-provider-fivetran/pull/7
