### ISSUE TITLE
Create a Fivetran managed connection

### ISSUE THREAD

**Issue by pgzmnk** [fivetran/airflow-provider-fivetran#3]
Airflow separates authentication layer from the workflow logic. To this end, Airflow stores information such as hostname, port, login, and passwords to other systems and services in an encrypted [metastore database](https://airflow.apache.org/docs/apache-airflow/stable/_api/airflow/secrets/metastore/index.html?highlight=metastore#module-airflow.secrets.metastore). DAGs access credentials by referencing the 'conn_id' of the Connection objects. This provides a managed layer of security and enables developers to focus on the workflow.

Airflow provides multiple ways to retrieve connections: from environment variables, the metastore database, manually via the API or CLI, or with a custom [Secrets Backend](https://www.astronomer.io/docs/cloud/stable/customize-airflow/secrets-backend). I prefer to pass credentials via a .env file when developing locally to make setup easier while developing, but it's highly encouraged to create connectors that are saved in the metastore when in production. Here's [documentation on managing connections](https://airflow.apache.org/docs/apache-airflow/stable/howto/connection.html).

The proposed Fivetran operator uses the requests library to interact with the Fivetran API, a good example to follow is the [HTTP package.](https://github.com/apache/airflow/blob/master/airflow/providers/http/operators/http.py)

- While creating the Hook, it's important to keep your preferred HTTP authentication method and its required parameters in mind.
- Hooks inherit from the `[BaseHook` method](https://github.com/apache/airflow/blob/master/airflow/hooks/base.py).  You'll notice on line [72 of the HTTP hook](https://github.com/apache/airflow/blob/master/airflow/providers/http/hooks/http.py#L72) how the get_connection retrieves credentials based on the user-provided connector id. The code that follows structures the request using the provided credentials.
- Headers can also be specified in the Extra field of the connector in json format. This might come in handy if authenticating with Bearer tokens e.g. `{"Content-Type": "application/json", "Authorization": "Bearer [token]"}`

You can create a connection in the connections UI panel: [http://localhost:8080/connection/list/](http://localhost:8080/connection/list/)

```
Conn Id     : fivetran_default
Conn Type   : HTTP   
Description : Connects to Fivetran API
Host        : https://api.fivetran.com/
Login       : API_KEY # Method 1 
Password    : API_SECRET # Method 1
Extra       : { "authorization": "Bearer [token]"} # Method 2
```

The http_default connection shows a sample configuration:

<img width="734" alt="Screen Shot 2021-02-22 at 6 36 11 PM" src="https://user-images.githubusercontent.com/27398253/108794089-6653ee80-7542-11eb-9ecd-b47201314cc0.png">

**Comment by crw** [comment]
Closed with https://github.com/fivetran/airflow-provider-fivetran/pull/7
