### ISSUE TITLE
Create a Fivetran Sensor

### ISSUE THREAD

**Issue by pgzmnk** [fivetran/airflow-provider-fivetran#4]
Airflow tasks come in two main flavors: Operators execute an explicit action and Sensors wait until a condition is met. For example, an Airflow Sensors might recurrently hit an API endpoint at a set (optionally, dynamic) time interval and either succeed when a condition is met or fail if and when it times out.

[Line 125 of the Fivetran Operator](https://github.com/fivetran/airflow-provider-fivetran/blob/main/airflow-provider-fivetran/operators/fivetran.py#L125) shows a while loop that pings an endpoint and sets execution state based on the response. This unit of logic is a good candidate for a sensor.

This pseudocode shows a sample DAG that uses both a Fivetran Operator and a Fivetran Sensor. Note the separation of concerns between authentication, 

```python
@dag(default_args=default_args, schedule_interval=None, catchup=False, start_date=days_ago(8), tags=['test'])
def my_workflow(poll_status_every_n_seconds: int = 60):
  """ 
  Example Fivetran DAG pseudocode.
  
  See Airflow 2.0 DAGs best practices here: 
  https://airflow.apache.org/blog/airflow-two-point-oh-is-here/
  
  :param poll_status_every_n_seconds: Customizeable time interval for sensor.
  :type poll_status_every_n_seconds: int
  """

  task1 = FivetranSyncJobOperator(
    task_id='task1',
    conn_id = 'fivetran_default'
    )
  
  sensor1 = FivetranSyncJobSensor(
    task_id='sense1',
    conn_id = 'fivetran_default',
    poke_interval="{{ dag_run.conf['poll_status_every_n_seconds'] }}" # Provide user-defined parameters
    )
  
  task1 >> sensor1

my_workflow_dag = my_workflow()
```

**How to create a Sensor**

Sensor operators are derived from the [BaseSensorOperator class](https://github.com/apache/airflow/blob/master/airflow/sensors/base.py#L41) and inherit its attributes. The BaseSensorOperator provides and documents parameters you can leverage, such as poke_interval (in seconds), exponential_backoff, and mode.

A good example of a related Sensor is the [HttpSensor](https://airflow.apache.org/docs/apache-airflow-providers-http/stable/operators.html#httpsensor) which "pokes" the endpoint until the response meets a certain condition.

**Comment by crw** [comment]
Closed with https://github.com/fivetran/airflow-provider-fivetran/pull/14

**Comment by raajpackt** [comment]
can we a sensor without an operator? What if i want to trigger multiple dags based on one fivetran connector?
