### ISSUE TITLE
The sensor does not get released after the load is done

### ISSUE THREAD

**Issue by leoch20** [fivetran/airflow-provider-fivetran#53]
Often the Fivetran sensor does not get released after the job was done. Instead it gets stock till the next dag execution.

This issue is more common with the Aurora Postgres connector and salesforce.

Please find attached two images for the Aurora Postgres connector. The Fivetran UI shows that this particular load took 4 minutes and 14 seconds to finish,

![Screenshot 2022-01-05 at 09 58 30](https://user-images.githubusercontent.com/29922536/148192390-908c1fb0-4b50-4e47-a353-b81c975e756f.png)

Whereas the airflow dag shows that the task took 1 hour and 3 minutes to complete. 

![Screenshot 2022-01-05 at 09 57 28](https://user-images.githubusercontent.com/29922536/148192414-5f4a159c-9528-46a4-b3e2-71f6ee43667f.png)

**Here is out configuration:**

We are using Amazon Managed Workflows for Apache Airflow (MWAA)
Airflow 2.0.2
Python 3.7
airflow-provider-fivetran==1.0.2

_I also created an internal Fivetran ticket, here is the ID for reference 51375_

**Comment by iamepps** [comment]
We are working with a similar issue where sensors hang. 

In our setup the root cause is that the airflow scheduler does not trigger the sensor task until after the connector has finished syncing. This is particularly a problem in more complex DAGs with several Fivetran syncs that have downstream dependencies. In this case, the airflow scheduler does not necessarily move straight from FivetranOperator -> FivetranSensor and the connector finishing syncing in the intervening period.

We are testing a solution - which is to write a new FivetranPatientOperator (see here: https://github.com/tes/airflow-provider-fivetran/blob/patient_operator/fivetran_provider/operators/fivetran.py#L87) that does will not complete until the connector is finished syncing (or failing).

**Comment by leoch20** [comment]
It sounds like a different issue. I can see the Fivetran sensor triggered right after the Fivetran Operator. Our problem is that the sensor runs till the next dag execution (we use hourly intervals).

I can also confirm from the Fivetran UI that the sync took just a few minutes, not an hour.

**Comment by iamepps** [comment]
🤔  yeah that does sound a little different. What do the airflow logs for your sensor task show? 

The sensor should log the connector id and the sync status each time it pokes the Fivetran API (to pull the connector status and check if `succeeded_at` / `failed_at` has increased from the point the task started at). e.g. 

```
...
[2021-12-16 17:05:34,148] {{fivetran.py:284}} INFO - Connector "assessors_sample": sync_state = scheduled
[2021-12-16 17:06:35,301] {{fivetran.py:284}} INFO - Connector "assessors_sample": sync_state = scheduled
...
```

**Comment by PubChimps** [comment]
Hi everyone, Nick from Fivetran here, looking into these issues now... thank you for letting us know

**Comment by alejobs** [comment]
Hi, we are experiencing the same exact error in our company. Any news on this?

**Comment by PubChimps** [comment]
Hi @alejobs, one suggestion we've seen work is to change the FivetranSensor's mode to reschedule, like below. You can also start the sensor and the same time or before the FivetranOperator to ensure it is running. Please let us know if you are still seeing this error and if this helps.

```
fivetran_sync_wait = FivetranSensor(
        task_id='fivetran-sensor',
        fivetran_conn_id='fivetran_default',
        connector_id="{{ var.value.connector_id }}",
        poke_interval=5,
        mode="reschedule",
    )
```

**Comment by armandduijn** [comment]
@PubChimps I'm still seeing the behavior described in the issue description when implementing your suggestion. Also, how do you suggest we start the sensor before the Fivetran Operator? They would need to run in parallel but, as far as I'm aware, you can't guarantee which task Airflow schedules first.

![image](https://user-images.githubusercontent.com/706385/156586786-d2821ad2-9694-477a-a73e-debbaa3149b4.png)
