### ISSUE TITLE
Document modules

### ISSUE THREAD

**Issue by pgzmnk** [fivetran/airflow-provider-fivetran#6]
We will share a doc on best practices to document & lint the package and its modules. 

In the meantime, these are key items to keep in mind:
- Document each module using reStructuredText as markup. It will automatically convert to HTML documentation with Sphinx.
- Create a class docstring for each module (hook, sensor, operator, etc.).
    - Leave the first line blank.
    - The first sentence is a brief summary of the purpose and behavior. [Write in active voice.](https://developers.google.com/tech-writing/one/active-voice)
    - (Optional) Write paragraphs that explain further important details that are useful to the developer.
    - Document class attributes and their types with the convention shown below.

```python
class HttpHook(BaseHook):
    """
    Interact with HTTP servers.

    :param method: the API method to be called
    :type method: str
    :param http_conn_id: connection that has the base API url i.e https://www.google.com/
        and optional authentication credentials. Default headers can also be specified in
        the Extra field in json format.
    :type http_conn_id: str
    :param auth_type: The auth type for the service
    :type auth_type: AuthBase of python requests lib
    """
```

**Comment by crw** [comment]
This is more to standard across the board, but I'd be interested in a quick review to let us know if we are matching the style guide, as it were.

**Comment by crw** [comment]
I believe this is fixed, please let me know how we can improve.
