### ISSUE TITLE
FivetranSensor missing syncs that complete before the sensor starts

### ISSUE THREAD

**Issue by ANich** [fivetran/airflow-provider-fivetran#60]
Hi, thanks for the work on this provider.

We've noticed an issue for syncs that complete quickly after being started by the `FivetranOperator`. The `FivetranSensor` starts and begins polling after the sync has completed, so it continuously receives a `scheduled` state until another sync is triggered or it's marked as SUCCESS externally. This leads to long-running sensors (daily syncs for e.g.).

You should be able to reproduce this with a connector that syncs quickly and a sleep operator between the `fivetran_sync_start` and the `fivetran_sync_wait`.

We've solved this by (1) removing the `fivetran_sync_start >> fivetran_sync_wait` dependency between the operator and the sensor so the sensor task doesn't block the operator task (2) setting sensor priority > operator priority so the sensor starts shortly before the operator. 

(Seems like something like https://github.com/fivetran/airflow-provider-fivetran/issues/49 may solve this. Perhaps identifying syncs could as well?)

**Comment by PubChimps** [comment]
Thanks Alexander, we are solving this in the next release of the provider with [XCOMs](https://airflow.apache.org/docs/apache-airflow/stable/concepts/xcoms.html). I should have this release out and instructions on how to use the provider w/ XCOMs this week, I'll then post the instructions here and close this issue

**Comment by PubChimps** [comment]
Please update to version 1.1.0 and see [this example](https://github.com/fivetran/airflow-provider-fivetran/blob/main/fivetran_provider/example_dags/example_fivetran_xcom.py) for how to catch short syncs
