### ISSUE TITLE
Unable to create connectin with Fivetran in Airflow V1.10.9

### ISSUE THREAD

**Issue by snitwalmntv** [fivetran/airflow-provider-fivetran#63]
Hi there ,

I am using Airflow V1.10.9 and unable to create connection in Airflow UI so that I can use it in the FivetranOperator as parameter

**Comment by PubChimps** [comment]
Hi thank you! I don't think custom connection types are available in that version of airflow. If you create a connection with HTTP as the Connection Type it will work

<img width="1728" alt="Screenshot 2022-11-29 at 3 30 01 PM" src="https://user-images.githubusercontent.com/30478672/204672222-269ca3e7-30ab-45f0-b846-1e648252f279.png">
